//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaeAchievement.res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YaeAchievement.res.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部成就.
        /// </summary>
        internal static string AllAchievement {
            get {
                return ResourceManager.GetString("AllAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 另一个实例正在运行，请关闭后重试.
        /// </summary>
        internal static string AnotherInstance {
            get {
                return ResourceManager.GetString("AnotherInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YaeAchievement - 原神成就导出工具 ({0}).
        /// </summary>
        internal static string AppBanner {
            get {
                return ResourceManager.GetString("AppBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动读取到游戏路径: {0}.
        /// </summary>
        internal static string ConfigInitGotPath {
            get {
                return ResourceManager.GetString("ConfigInitGotPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果确认路径无误，请按 Y ；若有误或需要自行选择，请按 N .
        /// </summary>
        internal static string ConfigInitPathConfirm {
            get {
                return ResourceManager.GetString("ConfigInitPathConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载地址: {0}.
        /// </summary>
        internal static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出至: 
        ///[0] 椰羊 (https://cocogoat.work/achievement, 默认)
        ///[1] SnapGenshin
        ///[2] Paimon.moe
        ///[3] Seelie.me
        ///[4] 表格文件
        ///[5] 寻空
        ///[6] 原魔工具箱
        ///输入一个数字 (0-6): .
        /// </summary>
        internal static string ExportChoose {
            get {
                return ResourceManager.GetString("ExportChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出失败, 请联系开发者以获取帮助.
        /// </summary>
        internal static string ExportToCocogoatFail {
            get {
                return ResourceManager.GetString("ExportToCocogoatFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在浏览器内进行下一步操作.
        /// </summary>
        internal static string ExportToCocogoatSuccess {
            get {
                return ResourceManager.GetString("ExportToCocogoatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成就数据已导出至 {0}.
        /// </summary>
        internal static string ExportToFileSuccess {
            get {
                return ResourceManager.GetString("ExportToFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新 SnapGenshin 至最新版本后重试.
        /// </summary>
        internal static string ExportToSnapGenshinNeedUpdate {
            get {
                return ResourceManager.GetString("ExportToSnapGenshinNeedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在 SnapGenshin 进行下一步操作.
        /// </summary>
        internal static string ExportToSnapGenshinSuccess {
            get {
                return ResourceManager.GetString("ExportToSnapGenshinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在小程序导入页面输入以下代码: {0}.
        /// </summary>
        internal static string ExportToWxApp1Success {
            get {
                return ResourceManager.GetString("ExportToWxApp1Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新寻空至最新版本后重试.
        /// </summary>
        internal static string ExportToXunkongNeedUpdate {
            get {
                return ResourceManager.GetString("ExportToXunkongNeedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在寻空中进行下一步操作.
        /// </summary>
        internal static string ExportToXunkongSuccess {
            get {
                return ResourceManager.GetString("ExportToXunkongSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原神正在启动 ({0}).
        /// </summary>
        internal static string GameLoading {
            get {
                return ResourceManager.GetString("GameLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏进程异常退出.
        /// </summary>
        internal static string GameProcessExit {
            get {
                return ResourceManager.GetString("GameProcessExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原神正在运行，请关闭后重试 ({0}).
        /// </summary>
        internal static string GenshinIsRunning {
            get {
                return ResourceManager.GetString("GenshinIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按任意键退出.
        /// </summary>
        internal static string PressKeyToExit {
            get {
                return ResourceManager.GetString("PressKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要重新获取数据，手动删除 cache\d1a8ef40a67a5929.miko 后重新启动 YaeAchievement.
        /// </summary>
        internal static string RefreshData {
            get {
                return ResourceManager.GetString("RefreshData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作被取消.
        /// </summary>
        internal static string SelectCanceled {
            get {
                return ResourceManager.GetString("SelectCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 国服/国际服主程序.
        /// </summary>
        internal static string SelectFilterName {
            get {
                return ResourceManager.GetString("SelectFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择主程序.
        /// </summary>
        internal static string SelectTitle {
            get {
                return ResourceManager.GetString("SelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已完成但未领取奖励.
        /// </summary>
        internal static string StatusFinished {
            get {
                return ResourceManager.GetString("StatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知.
        /// </summary>
        internal static string StatusInvalid {
            get {
                return ResourceManager.GetString("StatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已完成.
        /// </summary>
        internal static string StatusRewardTaken {
            get {
                return ResourceManager.GetString("StatusRewardTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未完成.
        /// </summary>
        internal static string StatusUnfinished {
            get {
                return ResourceManager.GetString("StatusUnfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新内容: 
        ///{0}.
        /// </summary>
        internal static string UpdateDescription {
            get {
                return ResourceManager.GetString("UpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭程序后, 将压缩包解压至当前目录即可完成更新..
        /// </summary>
        internal static string UpdateDownloadFinish {
            get {
                return ResourceManager.GetString("UpdateDownloadFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在下载更新包....
        /// </summary>
        internal static string UpdateDownloading {
            get {
                return ResourceManager.GetString("UpdateDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有可用更新: {0} =&gt; {1}.
        /// </summary>
        internal static string UpdateNewVersion {
            get {
                return ResourceManager.GetString("UpdateNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在上报错误信息....
        /// </summary>
        internal static string UploadError {
            get {
                return ResourceManager.GetString("UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用上一次获取到的成就数据.
        /// </summary>
        internal static string UsePreviousData {
            get {
                return ResourceManager.GetString("UsePreviousData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装完成后，重新打开 YaeAchievement.
        /// </summary>
        internal static string VcRuntimeAfterInstall {
            get {
                return ResourceManager.GetString("VcRuntimeAfterInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未安装 VcRuntime.
        /// </summary>
        internal static string VcRuntimeNotInstalled {
            get {
                return ResourceManager.GetString("VcRuntimeNotInstalled", resourceCulture);
            }
        }
    }
}
