//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaeAchievement.res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YaeAchievement.res.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all achievement.
        /// </summary>
        internal static string AllAchievement {
            get {
                return ResourceManager.GetString("AllAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close another instance..
        /// </summary>
        internal static string AnotherInstance {
            get {
                return ResourceManager.GetString("AnotherInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YaeAchievement ({0}).
        /// </summary>
        internal static string AppBanner {
            get {
                return ResourceManager.GetString("AppBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to login genshin impact before exporting..
        /// </summary>
        internal static string ConfigNeedStartGenshin {
            get {
                return ResourceManager.GetString("ConfigNeedStartGenshin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download: {0}.
        /// </summary>
        internal static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error ({0}: {1}).
        /// </summary>
        internal static string ExceptionNetwork {
            get {
                return ResourceManager.GetString("ExceptionNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to: 
        ///[0] Cocogoat (https://cocogoat.work/achievement, Default)
        ///[1] Snap.HuTao
        ///[2] Paimon.moe
        ///[3] Seelie.me
        ///[4] Csv file
        ///[5] Xunkong
        ///Input a number (0-5): .
        /// </summary>
        internal static string ExportChoose {
            get {
                return ResourceManager.GetString("ExportChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail, please contact developer to get help information.
        /// </summary>
        internal static string ExportToCocogoatFail {
            get {
                return ResourceManager.GetString("ExportToCocogoatFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported to cocogoat..
        /// </summary>
        internal static string ExportToCocogoatSuccess {
            get {
                return ResourceManager.GetString("ExportToCocogoatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported to {0}.
        /// </summary>
        internal static string ExportToFileSuccess {
            get {
                return ResourceManager.GetString("ExportToFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update SnapGenshin and retry..
        /// </summary>
        internal static string ExportToSnapGenshinNeedUpdate {
            get {
                return ResourceManager.GetString("ExportToSnapGenshinNeedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported to snap genshin..
        /// </summary>
        internal static string ExportToSnapGenshinSuccess {
            get {
                return ResourceManager.GetString("ExportToSnapGenshinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ExportToWxApp1Success {
            get {
                return ResourceManager.GetString("ExportToWxApp1Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update xunkong and retry..
        /// </summary>
        internal static string ExportToXunkongNeedUpdate {
            get {
                return ResourceManager.GetString("ExportToXunkongNeedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported to xunkong..
        /// </summary>
        internal static string ExportToXunkongSuccess {
            get {
                return ResourceManager.GetString("ExportToXunkongSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game process start ({0}).
        /// </summary>
        internal static string GameLoading {
            get {
                return ResourceManager.GetString("GameLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game exited..
        /// </summary>
        internal static string GameProcessExit {
            get {
                return ResourceManager.GetString("GameProcessExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update genshin and retry..
        /// </summary>
        internal static string GenshinHashError {
            get {
                return ResourceManager.GetString("GenshinHashError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close game before run this application. ({0}).
        /// </summary>
        internal static string GenshinIsRunning {
            get {
                return ResourceManager.GetString("GenshinIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error:.
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No write permission on {0}..
        /// </summary>
        internal static string NoWritePermission {
            get {
                return ResourceManager.GetString("NoWritePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit..
        /// </summary>
        internal static string PressKeyToExit {
            get {
                return ResourceManager.GetString("PressKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward not taken.
        /// </summary>
        internal static string StatusFinished {
            get {
                return ResourceManager.GetString("StatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string StatusInvalid {
            get {
                return ResourceManager.GetString("StatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string StatusRewardTaken {
            get {
                return ResourceManager.GetString("StatusRewardTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfinished.
        /// </summary>
        internal static string StatusUnfinished {
            get {
                return ResourceManager.GetString("StatusUnfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: 
        ///{0}.
        /// </summary>
        internal static string UpdateDescription {
            get {
                return ResourceManager.GetString("UpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update package....
        /// </summary>
        internal static string UpdateDownloading {
            get {
                return ResourceManager.GetString("UpdateDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has update: {0} =&gt; {1}.
        /// </summary>
        internal static string UpdateNewVersion {
            get {
                return ResourceManager.GetString("UpdateNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Updater {
            get {
                object obj = ResourceManager.GetObject("Updater", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload error to appcenter....
        /// </summary>
        internal static string UploadError {
            get {
                return ResourceManager.GetString("UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use previous fetched data? (yes|no).
        /// </summary>
        internal static string UsePreviousData {
            get {
                return ResourceManager.GetString("UsePreviousData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Visual C++ Redistributable....
        /// </summary>
        internal static string VcRuntimeDownload {
            get {
                return ResourceManager.GetString("VcRuntimeDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Visual C++ Redistributable....
        /// </summary>
        internal static string VcRuntimeInstalling {
            get {
                return ResourceManager.GetString("VcRuntimeInstalling", resourceCulture);
            }
        }
    }
}
